### ISSUE TITLE
[Holley DTZ541] Error while parsing SML message: Error: Wrong TL-Field 0x65 for Choice!

### ISSUE THREAD

**Issue by hacki11** [Apollon77/ioBroker.smartmeter#34]
Ich habe einen Holley DTZ541 mit fehlerhaft implementiertem SML.
Man könnte versuchen den Zähler zu unterstützen indem man einen Hack in die verwendete SML Lib einbaut.

Details siehe:
https://github.com/volkszaehler/libsml/issues/75

Workaround für libsml:
https://github.com/volkszaehler/libsml/pull/76

Thread:
https://forum.iobroker.net/topic/25091/holley-dtz541-sml-1-04/7

Scheinbar gefixt in neueren Lieferungen:
https://www.loxforum.com/forum/projektforen/loxberry/plugins/85702-neues-plugin-smartmeter-stromzähler-auslesen?p=206977#post206977

Ich habe meinen Netzbetreiber darauf aufmerksam gemacht, aber wie geahnt interessiert oder versteht das dort hinter dem Kontaktformular niemand.

**Comment by Gerhard1968** [comment]
Habe den gleichen Zähler. Mit der Weidmann/Emlog Testsoftware bekomme ich die Werte aber angezeigt (1.8.0/2.8.0 und Momentanleistung).

**Comment by Apollon77** [comment]
Vllt aus einer Charge mit gefixter Formware? ;-)

**Comment by Gerhard1968** [comment]
Kann sein. Aber mit deinem smartmeter geht's trotzdem leider nicht.Besteht die Aussicht das der holley irgendwann Mal geht ;-)GrußGerhardVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Apollon77/ioBroker.smartmeter] [Holley DTZ541] Error while parsing SML message: Error: Wrong TL-Field 0x65 for Choice! (#34)Von: Ingo Fischer An: "Apollon77/ioBroker.smartmeter" Cc: Gerhard1968 ,Comment Vllt aus einer Charge mit gefixter Formware? ;-)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Apollon77/ioBroker.smartmeter/issues/34?email_source=notifications\u0026email_token=ANSCP25LPQN4RKUITM445TLQQ3E7JA5CNFSM4I74ZR32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECMSHNA#issuecomment-546907060",
"url": "https://github.com/Apollon77/ioBroker.smartmeter/issues/34?email_source=notifications\u0026email_token=ANSCP25LPQN4RKUITM445TLQQ3E7JA5CNFSM4I74ZR32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECMSHNA#issuecomment-546907060",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hacki11** [comment]
Wenn ich Zeit finde kann ich den Workaround welcher nun in der volkszähler libsml ist und die Sml lib des smartmeters portieren

**Comment by Apollon77** [comment]
Das wäre interessant ... machs gern gegen meinen Fork https://github.com/Apollon77/OpenSML ... am ENde muss man es mit dem ENtwickler der Lib dann klären, aber der adapter kann auch meinen Fork nehmen

**Comment by hacki11** [comment]
https://github.com/Apollon77/OpenSML/pull/1

**Comment by hacki11** [comment]
@Apollon77, kannst du dann das aktualisieren der libs und die releases übernehmen?

**Comment by Apollon77** [comment]
Checke es morgen  danke!!!

**Comment by hacki11** [comment]
Bist du schon dazugekommen?

**Comment by Apollon77** [comment]
Dauert noch paar Tage. Ich bin gerade noch tief in der Finalisierung des js-controller 2.0 ...

**Comment by hacki11** [comment]
Falls ich irgendwie unterstützen oder etwas übernehmen soll, gib einfach Bescheid!
Grob würde ich mergen, opensml releasen, opensml in smartmeter einbinden, bei mir Testen und ggf. smartmeter releasen.

**Comment by Apollon77** [comment]
Js-Controller 2 hat mich etwas länger gebunden als gedacht. Abe Hat sich gelohnt. 

Generell korrekt, aber ich bin nicht der opensml lib maintainer. Nur contributor. Ich kann also erstmal nur einen pr machen und warten. 

Meistens baue ich ne GitHub Variante vom Adapter das man es testen kann. 

Ich räume gerade alle meine todos auf und dann geht weiter.

**Comment by hacki11** [comment]
Klaro, Prioritäten muss man setzen - eins nach dem anderen.

Den PR kann ich ja auch gegen sein Repo stellen, dann fällt das schonmal weg von dir.

**Comment by Apollon77** [comment]
Gern!, erwähne mich mit bzw schreib das es mit mir abgestimmt ist ... vllt hilfts ;-)

**Comment by Apollon77** [comment]
@hacki11 .... ... Danke ... weisst Du was ich gerade gesehen (und mich erinnert hab) ... ich bin inzwischen doch maintainer und hab sogar npm rechte ;-)) ich warte jetzt nen tag falls der andere OpenSML Dev was sagen will ... dann publishen wir :-)

... zu viele projekte ...

**Comment by Apollon77** [comment]
will be fixed in upcoming v 3.0.0

**Comment by Apollon77** [comment]
v3.0.0 on GitHub ... https://forum.iobroker.net/topic/27116/test-adapter-smartmeter-3-0-x please report back in forum
